[tool.poetry]
name = "virl2_client"
version = "0.0.1"
description = "VIRL2 Client Library"
authors = ["Simon Knight <simknigh@cisco.com>"]
license = "Apache-2.0"
include = ["examples/*"]
exclude = ["tests/**/*"]

[tool.poetry.dependencies]
python = "^3.6.8"
requests = "^2"

[tool.poetry.dev-dependencies]
pytest = "^5"
pytest-cov = "^2"
responses = "^0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
